### ISSUE TITLE
AddButton submits form

### ISSUE THREAD

**Issue by pfulop** [brijeshb42/medium-draft#10]
Hi,
If you use editor inside a form, the AddButton on the bottom for adding images behaves as submit button. Which means when I want to add image  it submits the whole form. So it's my polite request, if possible, to change button in AddButton to type="button" so the button doesn't behave as a submit button.

**Comment by pfulop** [comment]
thank you

**Comment by brijeshb42** [comment]
Thanks for the heads up. v[0.3.7](https://github.com/brijeshb42/medium-draft/tree/0.3.7) fixes this.
