### ISSUE TITLE
Is handlePastedText a mandatory prop?

### ISSUE THREAD

**Issue by andresgutgon** [brijeshb42/medium-draft#102]
## What?
[handlePastedText](https://github.com/brijeshb42/medium-draft/blob/5a7d6b35b0408a673b5968992a61772be604df76/src/editor.js#L508) breaks if not defined. 

It's necessary always define this prop?

I'm just doing this to avoid error:
``` javascript
  handlePastedText () {
    return true
  }
```

**Comment by brijeshb42** [comment]
Fixed. Update to 0.5.5

**Comment by andresgutgon** [comment]
Thanks, that was fast! 👏
