### ISSUE TITLE
Uncaught Error: Unknown DraftEntity key.

### ISSUE THREAD

**Issue by mezod** [brijeshb42/medium-draft#103]
I initially posted this issue here: https://github.com/facebook/draft-js/issues/1363 

But since I mostly copied the code from the SeparatorSideButton from this repo I thought maybe you stumbled upon this issue.

I have several instances of medium-draft, and all work smoothly except one, where, when I try to add a separator or an embed from the side buttons I get this error.

This is how my code looks like:

```
onClick() {
    const entityKey = Entity.create('separator', 'IMMUTABLE', {});
    this.props.setEditorState(
      AtomicBlockUtils.insertAtomicBlock(
        this.props.getEditorState(),
        entityKey,
        '-'
      )
    );
    this.props.close();
  }
```

I then saw you had updated this code here: https://github.com/brijeshb42/medium-draft/blob/master/src/example.js#L121
But the issue persists.

Again, what I find more awkward is that for all the other instances it works. The only difference is that the other instances of medium-draft are loaded with initial content, while the one that doesn't work is initially empty. I tried to explicitly initialize the EditorState with "this.refs.myeditor.initializeEditorState();" but the problem persists.

Sorry I know this might not be 100% related to medium-draft but any help is very welcome!

**Comment by brijeshb42** [comment]
Entity has been deprecated from 0.10 of draft-ja

**Comment by mezod** [comment]
Yeah, I tried doing it like you do in the examples

```
onClick() {
    let editorState = this.props.getEditorState();
    const content = editorState.getCurrentContent();
    const contentWithEntity = content.createEntity('separator', 'IMMUTABLE', {});
    const entityKey = contentWithEntity.getLastCreatedEntityKey();
    editorState = EditorState.push(editorState, contentWithEntity, 'create-entity');
    this.props.setEditorState(
      AtomicBlockUtils.insertAtomicBlock(
        editorState,
        entityKey,
        '-'
      )
    );
    this.props.close();
}
```

but the problem is still there... :/

**Comment by brijeshb42** [comment]
Do you have a demo somewhere?

**Comment by mezod** [comment]
I'll set one up. Is there any email or way to privately message you a test password?

**Comment by brijeshb42** [comment]
@mezod You can pm me on draft-js channel.

**Comment by IzaGz** [comment]
Whats is solution? got same problem unknown DraftEntity key.

**Comment by brijeshb42** [comment]
@IzaGz What version of draft are you using? The entity api has been deprecated. Try to update draft and then check.

**Comment by IzaGz** [comment]
@brijeshb42 I use "draft-js": "^0.9.1"

**Comment by brijeshb42** [comment]
Update to 0.10.* if that is not a problem. Otherwise you can downgrade the version of medium-draft01.11.2017, 16:30, "IzaGz" <notifications@github.com>:@brijeshb42 I use "draft-js": "^0.9.1"
