### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by butsjoh** [brijeshb42/medium-draft#106]
Hey, i am using the v1-scalable branch for some time now and i think it is worth pushing it to npm so everyone could benefit from it. A soon as you do that i could also start creating some PR's to add more functionality like ability to focus atomic blocks and drag them around in the editor. Also i have an implementation that will offer a custom toolbar for doing certain actions on blocks ala real medium (image position, ...)

**Comment by brijeshb42** [comment]
I am almost done. Just have to convert the example code to use the new plugin type functionality. Was caught up with my job so did not get time for the release.

**Comment by butsjoh** [comment]
@brijeshb42 Do you need any help with that? I can create a PR with the changes? It is getting urgent for us.

**Comment by brijeshb42** [comment]
@butsjoh Just released a beta version on npm. Install using `npm install medium-draft@beta`

**Comment by butsjoh** [comment]
Hi @brijeshb42. I was just wondering what the status of the current master is compared to this old beta version. Did some of the stuff that is currently available still going to work with the stuff that has been done on the beta branch or has it been abandoned. I want to try and bump to latest drafjs and would be nice if i could take the medium editor thing along.
