### ISSUE TITLE
addNewBlock, initial

### ISSUE THREAD

**Issue by adrianp12** [brijeshb42/medium-draft#109]
In the example for adding an image, the addNewBlock function has a parameter for data (the third parameter) seen here:
```
if (response.status === 200) {
          // Assuming server responds with
          // `{ "url": "http://example-cdn.com/image.jpg"}`
          return response.json().then(data => {
            if (data.url) {
              this.props.setEditorState(addNewBlock(
                this.props.getEditorState(),
                Block.IMAGE, {
                  src: data.url,
                }
              ));
            }
          });
```

I've been going through the source and it looks like you can add several different types, like Block.UNSTYLED or Block.H1. However, I can't figure out what the data object should be for other types. I was thinking something like {text:'hello') for Block.H1. 

Any recommendations would be greatly appreciated! Thanks

**Comment by brijeshb42** [comment]
`addNewBlock` adds an empty block of type given by 2nd argument. 3rd arg is the metadata associated with the block. This cannot be used to add blocks with initial text. This is what you want

```js
const addNewBlockWithText = (editorState, newType = Block.UNSTYLED, text) => {
  const selectionState = editorState.getSelection();
  if (!selectionState.isCollapsed()) {
    return editorState;
  }
  const contentState = editorState.getCurrentContent();
  const key = selectionState.getStartKey();
  const blockMap = contentState.getBlockMap();
  const currentBlock = getCurrentBlock(editorState);
  if (!currentBlock) {
    return editorState;
  }
  if (currentBlock.getLength() === 0) {
    if (currentBlock.getType() === newType) {
      return editorState;
    }
    const newBlock = currentBlock.merge({
      type: newType,
      data: getDefaultBlockData(newType, initialData),
      text: text // <- this is the change that you want
    });
    const newContentState = contentState.merge({
      blockMap: blockMap.set(key, newBlock),
      selectionAfter: selectionState,
    });
    return EditorState.push(editorState, newContentState, 'change-block-type');
  }
  return editorState;
};
```

**Comment by niwaa** [comment]
@brijeshb42 I am trying to add text using your code snippet but I don't think it is working...  All I need is a way to insert blocks of texts.

**Comment by gabeamaleoni** [comment]
Hey there, any update on this? I am in a similar situation in that I would like to force a focus/new block of text after a successful image upload. Currently when users upload an image they need to hit the `enter` key in order to proceed writing a narrative. Is there any way to force this enter-key or automatically add an empty text block after image upload? @brijeshb42  @niwaa
