### ISSUE TITLE
Uncaught TypeError: Cannot read property 'preventDefault' of undefined

### ISSUE THREAD

**Issue by pfulop** [brijeshb42/medium-draft#11]
Hi,

I am getting an error when I am trying to add picture:
`addbutton.js:146 Uncaught TypeError: Cannot read property 'preventDefault' of undefined`

I think when checking for prevent default, it would be nice to check for event itself too.

Also do you have any call to print it out as a html content for saving in db?

**Comment by brijeshb42** [comment]
Can you submit a pull request for the fix?

Also saving as HTML in db is not a good idea. You should save the string representation of `editorState` json in db and then when loading, simply reconstruct the data using `JSON.parse`.

### While saving

```javascript
JSON.stringify(convertToRaw(editorState.getCurrentContent()))
```


### While loading
```javascript
const data  = JSON.parse(dataThatWasSavedPreviously); // fetched using ajax
const newEditorState = EditorState.push(this.state.editorState, convertFromRaw(data));
this.setState({
    editorState: newEditorState,
});
```

**Comment by pfulop** [comment]
I will submit it later today.

And when you want to show the result text back to user?

**Comment by brijeshb42** [comment]
To get the HTML you will have to use come kind of renderer library that generates HTML from the draft-js data. Here is a list of some [libraries](https://github.com/nikgraf/awesome-draft-js#common-utilities).

**Comment by brijeshb42** [comment]
https://github.com/brijeshb42/medium-draft/commit/904270c4f5bc71fbcd4ed3cc4322278b615ca3d9 closes this. You can use the latest version.
