### ISSUE TITLE
Deprecation Warning for ImmutableJS

### ISSUE THREAD

**Issue by aldofunes** [brijeshb42/medium-draft#110]
Hello,

I am presented with a console warning whenever I edit the content (using React 16). Everything else works fine

The warning is:

```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version.
```

Best regards

**Comment by brijeshb42** [comment]
Which version of `medium-draft` are you using?

**Comment by aldofunes** [comment]
I'm using `^0.6.0-beta1` but it was the same with `0.5.5`

also, I'm using `immutable ^3.8.2`
