### ISSUE TITLE
Adding image scrolls page to top

### ISSUE THREAD

**Issue by DimaUlyanets** [brijeshb42/medium-draft#111]
When you click on side button '+' it scrolls user on top of the page. So user need to scroll down back to choose image for example. And after picking image it scrolls up second time. Reproducible on http://bitwiser.in/medium-draft/
Latest Chrome (Version 62.0.3202.75 (Official Build) (64-bit))

**Comment by Marshevskyy** [comment]
@DimaUlyanets, it happens to me when I trigger toolbar (icon which opens other icons like image/video ...). Then when I click on adding image, it works ok. 

Here is PR for @medium-draft team. https://github.com/brijeshb42/medium-draft/pull/113
 
It helped me to fix this issue locally.
@DimaUlyanets you can update your "node_modules/medium-draft/lib/components/addbutton.js"  based on my PR, until m-team merge my PR, or find another solution how to prevent this jumping.

**Comment by brijeshb42** [comment]
Merged #113
