### ISSUE TITLE
CODE/code-block constants in toolbarConfig

### ISSUE THREAD

**Issue by zachbradshaw** [brijeshb42/medium-draft#116]
Sorry if I've overlooked this, but how do you enable the editor to support inline code/code blocks? I see the `.md-inline-code` style rules in `lib/basic.css` and I'm importing that into my component file. Am I missing something? I would like to support both inline code with single backticks and code blocks with three backticks.

**Comment by zachbradshaw** [comment]
Digging through some more issues lead me to `constants.js` where the code block/inline code constants are, so I'm closing this issue. Thanks.

**Comment by zachbradshaw** [comment]
Is it not possible to use the `CODE` and `code-block` constants in the `toolbarConfig` prop?

 ```javascript
// my config
toolbarConfig={{
    block: ['header-three', 'code-block'],
    inline: ['BOLD', 'CODE']
}}
```

Result:
![screen shot 2018-01-12 at 12 43 30 pm](https://user-images.githubusercontent.com/5965135/34887925-405d4d20-f796-11e7-8632-5ee3d1a5eacb.png)

**Comment by brijeshb42** [comment]
You'll have to use `blockButtons` and `inlineButtons` prop. See [here](https://github.com/brijeshb42/medium-draft/wiki/Customising-the-Toolbar).
