### ISSUE TITLE
Coding without keyboard

### ISSUE THREAD

**Issue by SetCodesToFire** [brijeshb42/medium-draft#118]
This is an enhancement. I suggest we could integrate voice coding. This could be build using deep neural networks (sequence model).

Unlike voice to speech conversion, the network could be made intelligent enough to take "equals to" as a voice input and translate it to "=".

As well as similar features and rules could be defined.

This could be the future of mobile coding.

**Comment by brijeshb42** [comment]
This seems a little far fetched for such a simple project.
