### ISSUE TITLE
Export to markdown

### ISSUE THREAD

**Issue by tianshuo** [brijeshb42/medium-draft#12]
This could be outputted to markdown using html2markdown libraries. Some content may may need to be output as pure html.

**Comment by brijeshb42** [comment]
Exporting is not a part of this project. You can use whatever external library you want to convert to and from markdown/html.

**Comment by magician11** [comment]
@brijeshb42 I understand that import/export is not part of this project.

If I were to create a ContentState though saying using [draft-js-import-markdown](https://www.npmjs.com/package/draft-js-import-markdown), how would I initiate the EditorState? I can't use your [createEditorState(data)](https://github.com/brijeshb42/medium-draft/blob/master/src/model/content.js#L26) as it uses convertFromRaw and we already have a ContentState with this plugin.

I've tried directly doing something like `editorState: EditorState.createWithContent(contentState)`

which basically works. But then I notice highlighting of a linked work no longer is highlighted, even though in the markdown it has been changed to a link.

This issue disappears if I start with your createEditorState() with no arguments. I can see your decorator is doing some extra work.

Do you need convertFromRaw()? What data object do you pass in that you call createEditorState with an argument?

**Comment by brijeshb42** [comment]
The data object passed to `createEditorState ` is the output of `convertToRaw(this.state.editorState.getCurrentContent())`. Under the hoods, it applies the `Link` decorator. If you want to use `EditorState.createWithContent`, you should also pass a 2nd argument, that is the link decorator - 

```javascript
import { CompositeDecorator } from 'draft-js';
import { Link, findLinkEntities } from 'medium-draft';

const decorator = new CompositeDecorator([
  {
    strategy: findLinkEntities,
    component: Link,
  },
]);

var yourContentState;

// finally,
editorState: EditorState.createWithContent(yourContentState, decorator)
```

**Comment by magician11** [comment]
Yes, this works thanks @brijeshb42 

I understand how there is a performance hit using the second code sample by converting it to raw, then immediately converting it from raw. But given it only happens once from the constructor, I think it's probably worth it given the terseness of the code. And to keep my code more compatible with yours.. in case you update your decorator at some point.

**Comment by magician11** [comment]
@tianshuo You could use https://www.npmjs.com/package/draft-js-export-markdown

And use it like so

```
import { stateToMarkdown } from 'draft-js-export-markdown';

  onRTEchange = editorState => {
    console.log(stateToMarkdown(editorState.getCurrentContent()));
    this.setState({ editorState });
  }
```

This will only convert the content that can be turned into markdown. So everything in the toolbar except the `todo list` and the `highlight section` buttons.

@brijeshb42 is there a way to customise the toolbar? So that only [standard markdown buttons](https://en.wikipedia.org/wiki/Markdown) are present? I haven't worked out what you mean by sidebuttons yet.

**Comment by brijeshb42** [comment]
@magician11 I haven't gotten around to documentation yet, but you can take a look at the props that `Editor` from `medium-draft` accepts and their default values [here](https://github.com/brijeshb42/medium-draft/blob/master/src/editor.js#L52).
