### ISSUE TITLE
Cannot read property 'getSelection' of undefined

### ISSUE THREAD

**Issue by SanjitaSingha** [brijeshb42/medium-draft#127]
I have installed medium-draft editor through npm-

> npm install --save medium-draft
And used the editor as written in documentation. But I am getting error of 

> Cannot read property getSelection of undefined

**Comment by brijeshb42** [comment]
Can you give the exact stack trace and the version you are using?

**Comment by SanjitaSingha** [comment]
Thank you @brijeshb42  for you reply.  Actually I mistakenly used custom state in Editor component, after correcting it issue get resolved.
