### ISSUE TITLE
Component's children should not be mutated

### ISSUE THREAD

**Issue by magician11** [brijeshb42/medium-draft#13]
Everytime I choose a type of list (UL or OL) from the tooltip options, I get

> warning.js:36 Warning: Component's children should not be mutated.
>     in ol
>     in div (created by DraftEditorContents)
>     in DraftEditorContents (created by DraftEditor)
>     in div (created by DraftEditor)
>     in div (created by DraftEditor)
>     in div (created by DraftEditor)
>     in DraftEditor (created by MediumDraftEditor)
>     in div (created by MediumDraftEditor)
>     in div (created by MediumDraftEditor)
>     in MediumDraftEditor (created by CreateRecall)
>     in div (created by CreateRecall)
>     in CreateRecall (created by Playground)
>     in div (created by Playground)
>     in Playground (created by Relay(Playground))
>     in Relay(Playground) (created by RouterContext)
>     in StaticContainer (created by RouteContainer)
>     in RouteContainer (created by RouterContext)
>     in RouterContext (created by Router)
>     in StaticContainer (created by RelayReadyStateRenderer)
>     in RelayReadyStateRenderer (created by IsomorphicRenderer)
>     in IsomorphicRenderer (created by IsomorphicRelayRouterContext)
>     in IsomorphicRelayRouterContext (created by Router)
>     in ScrollBehaviorContext (created by Router)
>     in Router
>     in Provider
>     in AppContainer

**Comment by brijeshb42** [comment]
Its a react [issue](https://github.com/facebook/react/issues/7424).
