### ISSUE TITLE
Update editorState in CustomImageSideButton component

### ISSUE THREAD

**Issue by SanjitaSingha** [brijeshb42/medium-draft#130]
Hi, I'm using firebase database to store data. I have gone through your customizing side buttons example code. And tried to use your code, but I'm getting error of  - 'cannot read property props of undefined'
here is my code - 

     onChange(e) {
        const file = e.target.files[0];
       if (file.type.indexOf('image/') === 0) {
 
      var fileName = file.name;
      var storageRef = firebase.storage().ref(`/dataImages/${fileName}`);

      var uploadTask = storageRef.put(file);

      uploadTask.then(function(snapshot) {
        console.log('Uplaod', snapshot.downloadURL, snapshot);
        if(snapshot.state === 'success') {
          const editorData = data => {
             if (data.downloadURL) {
               const src = data.downloadURL;
               this.props.setEditorState(addNewBlock(
                 this.props.getEditorState(),
                 Block.IMAGE, {
                   src,
                 }
               ));
             }
           }
           return editorData(snapshot)
        }
      }).catch(error => { console.log('Error', error) });
    }
    this.props.close();
    }
    }

Here is the console error - 

    Error TypeError: Cannot read property 'props' of undefined
    at CustomImageSideButton.js:54
    at <anonymous>

error is from the line this.props.setEditorState

**Comment by brijeshb42** [comment]
Since you are using `function`, the context inside it is not bound to parent. Changing `function(snapshot) {` to `(snapshot) => {` might work.

**Comment by SanjitaSingha** [comment]
Thank you @brijeshb42 , error get resolved. But I got empty tag of figure element-

   <figure class="md-block-image"></figure>

**Comment by brijeshb42** [comment]
Can you give some more context. At least the code in this particular file

**Comment by SanjitaSingha** [comment]
Thank you so much. Now its working, it was my mistake. Since I removed the empty self closing tag before rendering.
