### ISSUE TITLE
Integration with another Draft.js plugin

### ISSUE THREAD

**Issue by willbryk720** [brijeshb42/medium-draft#134]
There is another draft.js plugin that requires that they import an editor like this:
`import Editor from 'draft-js-plugins-editor`

But medium-draft also imports its own Editor
`import Editor from "medium-draft";`

If I use the Editor from medium-draft, the plugin doesn't work. If I use the plugin editor, medium-draft doesn't work. Is there a way around this problem?

**Comment by verespej** [comment]
You can use a [named import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). My recommendation would be something along the lines of the following:

```
import { Editor as DraftEditor } from 'draft-js'
```

**Comment by brijeshb42** [comment]
You can import as 

`import MediumDraftEditor from 'medium-draft'`

**Comment by elie222** [comment]
Not sure this answered his question. Is it possible to combine this editor with the draft js plugins one? Or would the best be to fork the plugins editor package to use medium-editor instead of draftjs editor?
