### ISSUE TITLE
Using Block.ATOMIC is broken

### ISSUE THREAD

**Issue by Ethaan** [brijeshb42/medium-draft#140]
I'm using the following Workflow.

1.- User click on the `plus` icon.
2.- Sub menus appear and user can select `video`
3.- When user click `video` other form appears where user can paste url.
4.- when user submit url i call `addNewVideoToEditor`.

I have the same workflow for images, and this is how the `addNewImageToEditor` looks.

```
  addNewImageToEditor(src) {
    const { getEditorState, setEditorState } = this;

    setEditorState(addNewBlock(
      getEditorState(),
      Block.IMAGE, { src },
    ));
  }
```

So for `video` i'm doing.

```
  addNewVideoToEditor(url) {
    const { getEditorState, setEditorState } = this;

    setEditorState(addNewBlock(
      getEditorState(),
      Block.ATOMIC, { url }, // try with src already too.
    ));
  }
```
Now, this work for images great, and i'm inserting any kind of images, but for `atomic` i got.

`Uncaught TypeError: props.getEditorState is not a function`.

and i can see that came from this line.

https://github.com/brijeshb42/medium-draft/blob/master/src/components/blocks/atomic.js#L7

The only difference i can see is that `ImageBlock` access `getEditorState` from `blockProps.getEditorState` and `AtomicBlock` is accessing it directly from `props.getEditorState`

eve thought the implementation on.

https://github.com/brijeshb42/medium-draft/blob/master/src/components/customrenderer.js

is the same.

I'm missing something here?, i try to implement the example from your the `example.js` but i got the same error.

**Comment by blizzerand** [comment]
@Ethaan Hey, were you able to fix this? I am having the same issue.

**Comment by blizzerand** [comment]
I was able to fix this. For anyone facing this particular issue, I had to edit the lines `const content = props && props.blockProps.getEditorState().getCurrentContent();` and  `if (type === 'IMAGE' || type === 'image')`

```js
import PropTypes from 'prop-types';
// import './atomic.scss';

import React from 'react';

const AtomicBlock = (props) => {
  const content = props && props.blockProps.getEditorState().getCurrentContent();
  const entity = content.getEntity(props.block.getEntityAt(0));
  const data = entity.getData();
  const type = entity.getType();
  console.log(type);

  if (type === 'IMAGE' || type === 'image') {
    return (
      <div className="md-block-atomic-wrapper">
        <img role="presentation" src={data.src} />
        <div className="md-block-atomic-controls">
          <button>&times;</button>
        </div>
      </div>
    );
  }
  return <p>No supported block for {type}</p>;
};

AtomicBlock.propTypes = {
  block: PropTypes.object,
  getEditorState: PropTypes.func,
};
```
Maybe some upstream changes broke this particular module.

**Comment by blizzerand** [comment]
@brijeshb42 Hey Brijesh, thanks for getting back. Appreciate it.

 It appears like I ended up with atomic blocks although I am trying to work with images. When I upload the image, the class name is class="md-block-image" suggesting the block is indeed an image. However, when I export it (for publishing) and then importing it back, it's converted into an atomic block (md-block-atomic) rather being an image. Hence, I got into this thread. Can you suggest where I should be looking to debug this behavior? I am guessing something is messing it up at the exporter/importer modules? Any help would be great!

**Comment by blizzerand** [comment]
Thanks @brijeshb42, it was indeed a mistake with the way I had implemented import. Apologies for the trouble. Also thanks for pushing the code-block commit. :)

**Comment by Ethaan** [comment]
@brijeshb42 i finally got embed working, but i can't understand why i'm not getting the embed to be saved on the database to be later displayed.

i'm doing something like.

```
   post: {
       ...otherFields,
      content: mediumDraftExporter(content.getCurrentContent()),
  },
```

where `content` is `EditorState`

but this is what i get from `getCurrentContent`.

```
<p class="md-block-unstyled"><br/></p><figure class="md-block-atomic">E</figure><p class="md-block-unstyled"><br/></p>
```

On the FormEditor following your instructions, all is working great.

![screen shot 2019-01-15 at 1 49 36 pm](https://user-images.githubusercontent.com/8289486/51205861-75c8ce00-18cc-11e9-90c3-71e88d6f1e04.png)


But on the page where the post should be displayed as normal HTML, im doing this.

(following the demo)

```
  const editorState = createEditorState(convertToRaw(mediumDraftImporter(post.content)));

  const eHTML = exporter(editorState.getCurrentContent());
```

Any idea?

**Comment by Ethaan** [comment]
This is how its looking if i do.

`const rawContentState = convertToRaw(content.getCurrentContent());`

![screen shot 2019-01-15 at 2 17 32 pm](https://user-images.githubusercontent.com/8289486/51207428-5b90ef00-18d0-11e9-8d4a-1fc431165014.png)

and if i do.

```
import { convertToRaw, draftToHtml } from 'draft-js';

const rawContentState = convertToRaw(content.getCurrentContent());
const htmlContent = draftToHtml(rawContentState);
console.log(htmlContent);

```

I got an `Object` error.

```
TypeError: Object(...) is not a function
```
