### ISSUE TITLE
Does this module support to write code?

### ISSUE THREAD

**Issue by minhnhatspk** [brijeshb42/medium-draft#142]
As the title, I sometimes want to write some blocks of code in my post that I can use the highlighting library to highlight them in view mode.
see my attached:
![image](https://user-images.githubusercontent.com/21996261/47830542-e75da980-ddbe-11e8-8438-a24b35bb8928.png)

**Comment by brijeshb42** [comment]
At this moment, you can write code but it won't add syntax highlighting. You may want to checkout `draft-js-plugins` with `draft-js-prism-plugin`
