### ISSUE TITLE
Error 'addons' undefined

### ISSUE THREAD

**Issue by johnandblue** [brijeshb42/medium-draft#143]
After installing `medium-draft` I get in the console this error:
```
medium-draft.js:6 Uncaught TypeError: Cannot read property 'addons' of undefined
    at medium-draft.js:6
    at medium-draft.js:6
```
<img width="458" alt="screenshot 2018-11-09 at 20 58 06" src="https://user-images.githubusercontent.com/21159524/48279633-34e2b200-e462-11e8-913d-907cd6fd1ee6.png">

After looking into it, it has something to do with the module `react-addons-css-transition-group` but I cannot figure out how to solve it.

Has anyone experienced the same issue? Thanks!

**Comment by brijeshb42** [comment]
Can you try 

`npm install react-transition-group` or `yarn add `react-transition-group`

**Comment by johnandblue** [comment]
umd?

this is my `package.json`, in case there's something off, but it's a sandbox with the basics, create-react-app, draft.js, and medium-draft. 

```json
{
  "name": "editor-sandbox",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "draft-js": "^0.10.5",
    "markdown-draft-js": "^1.2.0",
    "medium-draft": "^0.5.7",
    "react": "^16.6.1",
    "react-dom": "^16.6.1"
  },
  "devDependencies": {
    "react-scripts": "2.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

**Comment by johnandblue** [comment]
Ok, I found the problem. You were right about the umd, 🤦🏻‍♂️

**Comment by brijeshb42** [comment]
Can you replicate this and create a public sandbox if possible. From the error message, it seems like medium-draft's umd build is loaded in the browser and it expects `React.addons` to be present. I'll probably have to release a new build but I want to make sure.

**Comment by johnandblue** [comment]
sure, I'll publish it in a few hours ;)

**Comment by johnandblue** [comment]
As promise, here is the public repo: 
https://github.com/johnandblue/editor-sandbox
where you can replicate the error in the console due  to my obvious error on using the umd incorrectly. Let me know if you have some troubles with it. 
Cheers!

**Comment by janaka120** [comment]
@johnandblue how do you solve this problem
