### ISSUE TITLE
image missing when Loading HTML exported using medium-draft-exporter to editorState

### ISSUE THREAD

**Issue by luohaisi** [brijeshb42/medium-draft#144]
`const html = ''<div class="md-block-image-inner-container"><img role="presentation" src="https://image" /></div>'';
  const editorState = createEditorState(convertToRaw(mediumDraftImporter(html)));`

why `<img>` tag missing?

**Comment by brijeshb42** [comment]
The html should have the same format as it had when it was exported. In this case, 

```html
<figure class="md-block-image">
  <img src="https://youimage.url" alt="" />
</figure>
```
