### ISSUE TITLE
Support latest React version

### ISSUE THREAD

**Issue by jerryzhao0423** [brijeshb42/medium-draft#145]
I don't know if anyone still maintaining this project. Is it possible to update the React version support soon? I saw there were pull requests but they were a long time ago and still not merged.

**Comment by brijeshb42** [comment]
Published version `0.5.8` which fixes issue when using UMD build of this package. Previous versions also supported React 16. You just had to update it in your `package.json`.

**Comment by jerryzhao0423** [comment]
> Published version `0.5.8` which fixes issue when using UMD build of this package. Previous versions also supported React 16. You just had to update it in your `package.json`.

My current react version is 16.6.1. It works normally but npm still gives me a waring:
npm WARN medium-draft@0.5.8 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by brijeshb42** [comment]
`0.5.9` should fix that

**Comment by jerryzhao0423** [comment]
Looks all good now. Thanks
