### ISSUE TITLE
Automatically add a new block after image upload

### ISSUE THREAD

**Issue by gabeamaleoni** [brijeshb42/medium-draft#156]
I would like to force a focus/new block of text after a successful image upload. Currently when users upload an image they need to hit the `enter` key in order to proceed writing a narrative. Is there any way to force this `enter` key or automatically add an empty text block after image upload?  I have tried faking the `enter` key using JS on a successful server response for image, but it does not work. Thanks in advance!

**Comment by brijeshb42** [comment]
You can checkout [addNewBlock](https://github.com/brijeshb42/medium-draft/blob/master/src/model/index.js#L32) function and try to call it in your image success callback
