### ISSUE TITLE
Customizing the toolbar

### ISSUE THREAD

**Issue by oreodunno** [brijeshb42/medium-draft#157]
Love the toolbar.  Is there a way to customize the button order? Putting inline buttons before the block buttons?

Also, is there a way to make one of the buttons in the toolbar a dropdown menu that has several related options to pick from? 

If anyone could point me to where I can customize the toolbar's UX, that greatly help adoption. 

Thank you.

**Comment by brijeshb42** [comment]
You can customize the ordering and [buttons](https://github.com/brijeshb42/medium-draft/wiki/Customising-the-Toolbar) but there is no way to use dropdowns

**Comment by oreodunno** [comment]
Appreciate the answer!
