### ISSUE TITLE
Using 0.5.10 causes react-hot-loader error (0.6.0-beta1 does not)

### ISSUE THREAD

**Issue by kylebebak** [brijeshb42/medium-draft#159]
First off, congrats on the great library. It's really really awesome, and has been almost exactly what I was looking for.

I'm not sure if this will be a problem going forward, and it's not even a problem for me anymore because I upgraded to the 0.6.0 beta release.

When using the last stable version, 0.5.10, importing `Editor` would cause my app to throw an error saying more or less that **react-hot-loader** couldn't be found in `node_modules/medium-draft/lib`.

My `package.json` looked like this:

```json
"dependencies": {
    "@babel/polyfill": "^7.2.5",
    "@sentry/browser": "^4.5.3",
    "antd": "^3.13.1",
    "dayjs": "^1.8.0",
    "draft-convert": "^2.1.4",
    "lodash": "^4.17.11",
    "medium-draft": "^0.5.10",
    "prop-types": "^15.6.2",
    "qs": "^6.6.0",
    "react": "^16.7.0",
    "react-dnd": "^7.0.2",
    "react-dnd-html5-backend": "^7.0.2",
    "react-dom": "^16.7.0",
    "react-dropzone-uploader": "^2.5.1",
    "react-redux": "^6.0.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.3",
    "react-select": "^2.3.0",
    "redux": "^4.0.1",
    "redux-form": "^8.1.0",
    "redux-form-antd": "^3.1.9",
    "reselect": "^4.0.0",
    "whatwg-fetch": "^3.0.0"
  },
```

My app is built with CRA, pretty standard deps, and very up-to-date. None of my deps used `react-hot-loader` so this error was kind of puzzling. **medium-draft** was depending on it somehow. It doesn't seem like react-hot-loader should be a library dependency, at least not for a production build.

It might be a good idea to mention this in the README, or cut a new stable release ASAP so people don't run into this issue. Again, using **0.6.0-beta1** I don't run into this problem.

Thanks for the awesome work!

**Comment by brijeshb42** [comment]
Its only a dev dependency and not a main dep. Can you paste the exact error?

**Comment by kylebebak** [comment]
I reinstalled 0.5.10 and ran it again. Here's the error:

```
Failed to compile.

./node_modules/medium-draft/lib/index.js
Module not found: Can't resolve 'react-hot-loader' in '/Users/kylebebak/Code/Work/Almanac/almanac-editor/node_modules/medium-draft/lib'

```

This error is thrown if I load any screen in my app, even screens that don't import `Editor` from `medium-draft`.

Importing `Editor` from `medium-draft` anywhere causes the error to be thrown. Again, I'm using a very vanilla project config with CRA, and I don't have a `react-hot-loader` dep anywhere. The error goes away if I use 0.6.0.

**Comment by kylebebak** [comment]
Cool =)
