### ISSUE TITLE
Is there a way to customize the link icon (#)?

### ISSUE THREAD

**Issue by madshargreave** [brijeshb42/medium-draft#16]
As the title says, I'd like to display a chain icon, instead of the hashtag for the inline-toolbar

Is this possible?

**Comment by brijeshb42** [comment]
The icon feature will be in upcoming version. Right now, only text is accepted.

**Comment by magician11** [comment]
Is it possible to hide that link button altogether? We're not going to be using it.

It [seems to be hardcoded](https://github.com/brijeshb42/medium-draft/blob/master/src/components/toolbar.js#L225).

**Comment by brijeshb42** [comment]
@magician11 Yes, the link button is hardcoded because it has slightly different functionality than other inline buttons. I have not been able to figure out how to make it more generic. Any ideas are welcome.
There is a different way to not show the link button though. You can use CSS to hide it by targeting the `RichEditor-linkButton` class.

**Comment by magician11** [comment]
@brijeshb42 

Yes, I figured out how to hide the last element using CSS..

```
.RichEditor-controls:last-child {
    display: none;
}
```
Which gives something like this..

![screen shot 2016-10-25 at 3 36 49 pm](https://cloud.githubusercontent.com/assets/3735849/19678710/0b6c7a76-9ac9-11e6-9e24-f8cf9ca414f1.png)


But the width of the toolbar then still needs to also be adjusted. And I'm not sure I can override an inline style like that.

![screen shot 2016 10 25 at 3 32 31 pm](https://cloud.githubusercontent.com/assets/3735849/19678723/18d735f2-9ac9-11e6-8dac-84a19a4dbb6c.png)

**Comment by brijeshb42** [comment]
I forgot to mention that the width is calculated dynamically and then set. So there is no way around that for now. I may have to add a custom Toolbar component prop for `Editor`.

**Comment by brijeshb42** [comment]
@magician11 I have just released v0.3.11 which accepts `hyperlink` object in `inlineButtons` array. Take a look at the updated wiki.

**Comment by Method-X** [comment]
@brijeshb42 Any plans to add support for code blocks?

**Comment by brijeshb42** [comment]
@Method-X Code blocks won't be directly available in `medium-draft`.  But you can extend it through the the props to support code blocks yourself. I am working on the docs. But you can read the source to know how to do that.

**Comment by drewbrolik** [comment]
In the meantime before the icon feature, using the 🔗  emoji is a workaround if you want a link icon. I have no idea how supported that is, but it seems to be working for me.

**Comment by brijeshb42** [comment]
There is now a way to customize all icons. You can now pass react components as `label`. See https://github.com/brijeshb42/medium-draft/blob/master/src/components/toolbar.js#L350
