### ISSUE TITLE
Get medium draft html with inline css?

### ISSUE THREAD

**Issue by truongthanhtungitvn** [brijeshb42/medium-draft#163]
Hi guys,
I'm using medium-draft to create a reminder app, it has email notification and I got an issue how to show the html content in the email template.
I need to render the html with inline css, how medum-draft can export rendered html with inline css?
currently I applied this code
`const renderedHTML = mediumDraftExporter(editorState.getCurrentContent());`

it looks like this in the editor
<img width="377" alt="1_medium_editor" src="https://user-images.githubusercontent.com/3183707/54890997-6ecac700-4ede-11e9-8b3f-cae3ce704488.png">
and in the email 
<img width="263" alt="1_medium_email_content" src="https://user-images.githubusercontent.com/3183707/54891002-74281180-4ede-11e9-91f9-012b5e61b71d.png">

I need it looks the same, please help me, thanks.

**Comment by brijeshb42** [comment]
You have to look for some other tooling to do that for you. `medium-draft` is a rich text editor and is only concerned with editing. You can take a look at `https://github.com/Automattic/juice`.

Using this, you can pass this string to `juice` to get inlined css -

```js
const fs = require('fs');
const juice = require('juice');
const renderedHTML = mediumDraftExporter(editorState.getCurrentContent());

// This is one way. There may be other ways as well.
const mainCss = fs.readFileSync(`/path/to/node_modules/medium-draft/dist/basic.css`);
const inlinedHTMLwithCss = juice(`<style>${mainCss}</style><div>${renderedHTML}</div>`);
```

**Comment by truongthanhtungitvn** [comment]
> You have to look for some other tooling to do that for you. `medium-draft` is a rich text editor and is only concerned with editing. You can take a look at `https://github.com/Automattic/juice`.
> 
> Using this, you can pass this string to `juice` to get inlined css -
> 
> ```js
> const fs = require('fs');
> const juice = require('juice');
> const renderedHTML = mediumDraftExporter(editorState.getCurrentContent());
> 
> // This is one way. There may be other ways as well.
> const mainCss = fs.readFileSync(`/path/to/node_modules/medium-draft/dist/basic.css`);
> const inlinedHTMLwithCss = juice(`<style>${mainCss}</style><div>${renderedHTML}</div>`);
> ```

thank you so much
