### ISSUE TITLE
Move away from embedly?

### ISSUE THREAD

**Issue by kwayebopp** [brijeshb42/medium-draft#165]
This is a pretty slick library, thanks for working on it. My one gripe is the use of embedly for embedding linked content. The branding is distracting and kinda takes up a bunch of space. I have seen that the [Dante2](https://github.com/michelson/dante2) library makes use of [Noembed](https://noembed.com/) which (IMO) appears much cleaner without the branding. I'm curious to hear other thoughts on this.

**Comment by brijeshb42** [comment]
Embedly is just used on the demo page as an example. The actual editor has no notion of an embed service. You are free to choose anything you want. You can take a look at `src/example.js` to see how embedly is being used and change accordingly as per your needs.
