### ISSUE TITLE
How to catch toolbar button click

### ISSUE THREAD

**Issue by janaka120** [brijeshb42/medium-draft#169]
Thanks for this amazing project.

@brijeshb42 If there is any way to catch toolbar button click or add new component to toolbar.

**Comment by brijeshb42** [comment]
https://github.com/brijeshb42/medium-draft/wiki/Customising-the-Toolbar

**Comment by janaka120** [comment]
According to this we use only these H3, Q, UL, OL, Todo list item, B, I, U, Hi and Add link items only. I need to add new button to toolbar some like share button. Can I achieve this.

**Comment by brijeshb42** [comment]
Nothing such is inbuilt. Maybe you can submit a PR that will call an `onClick` prop if present in the toolbar config itme

**Comment by janaka120** [comment]
@brijeshb42 I added a `onClick` prop for toolbar config item. How can I send a PR for that ?

**Comment by brijeshb42** [comment]
You need to fork this project, then clone and make changes, push the changes to your fork on github first

**Comment by janaka120** [comment]
@brijeshb42  I make a PR. Please check https://github.com/brijeshb42/medium-draft/pull/170
