### ISSUE TITLE
Supplying custom stylemaps

### ISSUE THREAD

**Issue by madshargreave** [brijeshb42/medium-draft#18]
Hi 

I'd like to supply my own stylemap to the editor like so

import { Block, Inline } from '../constants';

```
const emailStyleMap = {
  [Block.H1]: {
    fontWeight: 300,
    ...  
  },
};
```

I pass this as a prop on the editor, but it does not get applied.

Any ideas?

**Comment by brijeshb42** [comment]
Stylemap is only applicable for inline items like bold, italic and not for the whole block. For block styling, you will have to pass blockStyleFn.
