### ISSUE TITLE
How to get text from editorState?

### ISSUE THREAD

**Issue by Method-X** [brijeshb42/medium-draft#20]
I started using React about a week ago and am still adjusting to common patterns and conventions. You'll have to excuse me if this is completely obvious but editorState doesn't return any text content so far as I can tell...

**Comment by brijeshb42** [comment]
@Method-X Can you goto the editor demo, open developer tools and then click on Log State button. It will log the editor data. You will see the JSON data logged. That is what is stored in the editor state.

**Comment by Method-X** [comment]
Ah! I just wasn't looking hard enough through the object.

`this.state.editorState.getCurrentContent().getPlainText()`
