### ISSUE TITLE
How to delete the image (from database) after using backspace in editor?

### ISSUE THREAD

**Issue by abhishekjalan87** [brijeshb42/medium-draft#202]
If suppose user uploaded the image but later he decided to remove the image using backspace or delete then how it will delete from the database. 
Currently, it's not deleting from the database and creating the junks. 

Please advise

**Comment by brijeshb42** [comment]
Seems use case specific. Draft-js does not have listener that provides only the changed data. There are various other ways to do this. For example, if the current block is image and backspace is pressed, you can trigger your db delete.
