### ISSUE TITLE
Using this component on mobile devices

### ISSUE THREAD

**Issue by magician11** [brijeshb42/medium-draft#21]
There are a few issues we've come across when trying to use this component on mobile devices.

1) the native toolbar (copy, paste) sits on top of this component's rich text editor tooltip

![bs_realios_mobile_iphone 6s plus-9 0](https://cloud.githubusercontent.com/assets/3735849/19749273/2cdf9496-9c12-11e6-912c-e350af3cfb29.jpg)

2) The tooltip is often partly off the screen

![screen shot 2016-10-27 at 6 54 30 am](https://cloud.githubusercontent.com/assets/3735849/19749315/56f54cc6-9c12-11e6-8222-18e3dac2fcce.png)

So we're thinking of disabling it outright for mobile devices. Is there a prop or something similar we can do to disable the tooltip?

Any other thoughts or suggestions? It looks like medium.com for instance doesn't allow rich text editing on mobile devices. You need to use the desktop or download their native app (which extends the native toolbar and keyboard).

**Comment by brijeshb42** [comment]
Next update will have option to disable toolbar.

**Comment by magician11** [comment]
Great thanks @brijeshb42 Just drop me a note here when you do that update, and I'll do the update on our end.

**Comment by brijeshb42** [comment]
v0.3.12 has an option to disable toolbar using `disableToolbar` prop. Set it to `true` to disable it.

**Comment by magician11** [comment]
Awesome. Thanks.

We're using it like this now..

```
    // check to see whether this device is a touchscreen. If so, disable the tooltip editor
    const isTouchDevice = 'ontouchstart' in document.documentElement;

    return (
      <Editor
        editorState={this.state.editorState}
        onChange={this.onChange}
        inlineButtons={INLINE_BUTTONS}
        disableToolbar={isTouchDevice}
        blockButtons={BLOCK_BUTTONS} />
    );
```
