### ISSUE TITLE
Is this maintained anymore? Possible outdated draftjs causing block is not a BlockNode error

### ISSUE THREAD

**Issue by StarAzure** [brijeshb42/medium-draft#213]
Looks like draft js version you are using is very old - v0.10.0. 

Getting error Invariant Violation: `block is not a BlockNode` when using convertToRaw.

Looks like a good library but wanted to check if its maintained. If so, what would be the resolution for block is not a BlockNode error when using with draftjs 0.11.7 ?

**Comment by StarAzure** [comment]
Can you bump the version of **draft js** which is actually the core to a more recent stable version?

**Comment by kishan-tocca** [comment]
> Looks like draft js version you are using is very old - v0.10.0.
> 
> Getting error Invariant Violation: `block is not a BlockNode` when using convertToRaw.
> 
> Looks like a good library but wanted to check if its maintained. If so, what would be the resolution for block is not a BlockNode error when using with draftjs 0.11.7 ?

facing same issue

**Comment by bmknaidu555** [comment]
Hey... I don't think so. Checkout editor.js (Medium like editor) once. It is well maintained and also has many plugins. I am sure you will really like it.

**Comment by StarAzure** [comment]
Using editorjs instead. Clising.
