### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by riccardolorenzon** [brijeshb42/medium-draft#22]
hi, 

I'm trying to get a placeholder on my Editor with no success, what i did coming, from the [draft js docs](https://facebook.github.io/draft-js/docs/api-reference-editor.html), is adding a `placeholder` property to the Editor component, unfortunately it doesn't work.

**Comment by brijeshb42** [comment]
have you included the css for `medium-draft` ?

**Comment by Method-X** [comment]
We could better help if you showed us some code @riccardolorenzon.

**Comment by riccardolorenzon** [comment]
@brijeshb42 Yes i included the css by using `import 'medium-draft/lib/index.css';`. 
I see the style is applied for to the component.

@Method-X the code of the `render` method is pretty straightforward, but maybe is worth to report: 

```
return (
 <Editor
        sideButtons={{}}
        ref='editor'
        editorState={editorState}
        inlineButtons={inlineButtons}
        onChange={this.onChange}
        placeholder='Type your text' />);
``` 

Obviously i'm expecting the placeholder 'Type your text' when the text area is empty, but i don't get any text unfortunately.

**Comment by brijeshb42** [comment]
The value of `sideButtons` should be an empty array, not an empty object. Maybe that is causing the error.

**Comment by riccardolorenzon** [comment]
i changed the value of `sidebuttons` to `{[]}`. 

Still no placeholder displayed, and no message on console as well.

**Comment by brijeshb42** [comment]
Is there a demo you can share?

**Comment by riccardolorenzon** [comment]
@brijeshb42 a demo not quickly, but i can share my whole React class: 

```
const React = require('react');
import { Editor, createEditorState } from 'medium-draft';
import 'medium-draft/lib/index.css';

const CustomEditor = React.createClass({
  getInitialState: function() {
    return {
      editorState: createEditorState(),
    }
  },

  componentDidMount() {
    this.refs.editor.focus();
  },

  onChange: function(editorState) {
    this.setState({editorState: editorState});
  },

  render: function() {
    const {editorState} = this.state;
    var inlineButtons = [{
      label: 'B',
      style: 'BOLD',
      icon: 'bold',
      description: 'Bold',
    }, {
      label: 'I',
      style: 'ITALIC',
      icon: 'italic',
      description: 'Italic',
    }, {
      label: 'U',
      style: 'UNDERLINE',
      icon: 'underline',
      description: 'Underline',
    }, {
      label: 'S',
      style: 'STRIKETHROUGH',
      icon: 'strikethrough',
      description: 'Strikethrough',
    }, {
      label: '#',
      style: 'hyperlink',
      icon: 'link',
      description: 'Add a link',
    }];

    return (
      <Editor
        sideButtons={[]}
        ref='editor'
        editorState={editorState}
        inlineButtons={inlineButtons}
        onChange={this.onChange}
        placeholder='Type your text' />);
  }
});

module.exports = CustomEditor;
```

**Comment by brijeshb42** [comment]
The above code is working fine for me. I only had to change the `export` statement. Are you able to perform other editing operations except the placeholder ?

**Comment by riccardolorenzon** [comment]
All the other operations are working fine.. Can you see the placeholder then?

**Comment by brijeshb42** [comment]
Yes. The Placeholder was working fine.

<img width="791" alt="screen shot 2016-11-01 at 5 41 21 pm" src="https://cloud.githubusercontent.com/assets/717550/19889354/75ca7878-a05a-11e6-9fda-7acc0fe34c8b.png">

Now, all I can think of the error may be something to do with the CSS. `z-index` or `position`

**Comment by riccardolorenzon** [comment]
If i check the HTML i see a `#placeholder-23s09` div: 
```
<div class="DraftEditor-root">
      <div class="public-DraftEditorPlaceholder-root">
         <div class="public-DraftEditorPlaceholder-inner" id="placeholder-23s09">Type your text</div>
      </div>
     [...]
</div>
```

I don't see any particular style of RichEditor from overridden by my CSS though...

**Comment by riccardolorenzon** [comment]
UPDATE: if i remove `position:absolute` from the style of the class `public-DraftEditorPlaceholder-root` i see the placeholder.

**Comment by riccardolorenzon** [comment]
I think this is a CSS issue, wondering how come it works on your environment.

**Comment by brijeshb42** [comment]
You can use inspect element to check if anything is overriding the default style. 
On Nov 1, 2016 6:14 PM, riccardo lorenzon <notifications@github.com> wrote:I think this is a CSS issue, wondering how come it works on your environment.

**Comment by riccardolorenzon** [comment]
I don't see any overrides for that class.

**Comment by riccardolorenzon** [comment]
After some investigation i found out that he problem is due to my custom css stylesheet.
