### ISSUE TITLE
Set style for Image 

### ISSUE THREAD

**Issue by KhaMinhVLU-2017** [brijeshb42/medium-draft#224]
Can you help me set style for image ?
I reading your source code, I don't see you allow set style
![image](https://user-images.githubusercontent.com/31025072/123828928-32436c80-d92c-11eb-92a5-e4729e5ea098.png)

**Comment by brijeshb42** [comment]
You cannot directly set class or style. But you can override the styling in your css by target this classname `md-block-image-inner-container`

**Comment by KhaMinhVLU-2017** [comment]
OK thanks you
