### ISSUE TITLE
Strikethrough command

### ISSUE THREAD

**Issue by riccardolorenzon** [brijeshb42/medium-draft#23]
In the demo i see that the Link command(with the symbol #) has a tooltip mentioning 'strikethrough', which is clearly not true. 

Anyway i really need the link and the strikethrough commands, any idea on how to get the latter?

**Comment by brijeshb42** [comment]
Read [Customising the Toolbar](https://github.com/brijeshb42/medium-draft/wiki/Customising-the-Toolbar)

**Comment by riccardolorenzon** [comment]
Thanks!
