### ISSUE TITLE
Disabling popover when readonly

### ISSUE THREAD

**Issue by madshargreave** [brijeshb42/medium-draft#25]
Hi

Is it possible to disable the link mouse/popover when the editor is readOnly?

**Comment by gschlabitz** [comment]
Here's a workaround for now:

```
<Editor
    editorEnabled={false}
    editorState={createEditorState(contents)}
    onChange={()=>{}}
    blockButtons={[]}
    inlineButtons={[]}
/>
```
Essentially you customize the toolbar with "nothing."

**Comment by gschlabitz** [comment]
Or even easier:

```
<Editor
    editorEnabled={false}
    editorState={createEditorState(contents)}
    onChange={()=>{}}
    disableToolbar={true}
/>
```

**Comment by brijeshb42** [comment]
@gschlabitz - @madshargreave was referring to the tooltip that appears on hovering over a link text regardless of whether editor is enabled or disabled.

@madshargreave Next update will have classes in editor div based on whether whether it is enabled/disabled. That will help you in disabling tooltip if you choose it.

**Comment by madshargreave** [comment]
@brijeshb42  awesome

**Comment by brijeshb42** [comment]
New release has classes based on the editor is enable/disabled. You can use that to hide the tooltip using CSS
