### ISSUE TITLE
Don't require onChange prop, when editorEnabled is false

### ISSUE THREAD

**Issue by gschlabitz** [brijeshb42/medium-draft#26]
Easily remedied by giving it a dummy function, but would be nice if that isn't required.

`<Editor editorEnabled={false} editorState={editorState} onChange={()=>{}} />`

**Comment by brijeshb42** [comment]
`onChange` is required by `draft-js` editor. Although internally, `medium-draft` can have a default prop of `onChange` function that does nothing (like yours `onChange={()=>{}}`). But its inclusion depends on various use-cases. Open to discussion.

**Comment by brijeshb42** [comment]
This isn't required to be in the editor directly. You can use your solution that you mentioned.
