### ISSUE TITLE
Can we use draft js plugins with medium-draft? For example mentions plugin

### ISSUE THREAD

**Issue by cutbko** [brijeshb42/medium-draft#30]
https://www.draft-js-plugins.com/plugin/mention

**Comment by brijeshb42** [comment]
`medium-draft` is not compatible with `draft-js-plugins`.

**Comment by smeijer** [comment]
Is this still the case? The editor is looking awesome. But I do need mentions and emoji's.

**Comment by brijeshb42** [comment]
Yes. Still the case.

**Comment by wahengchang** [comment]
sad to found this issue , it such a pity , i need to integrate with code editor and prims plugin. :(

**Comment by indranshastri** [comment]
Is this still the case
I want to use resize and alignment of  image any other option may be
