### ISSUE TITLE
Is version 0.3.13 stable?

### ISSUE THREAD

**Issue by riccardolorenzon** [brijeshb42/medium-draft#31]
Hi

for some reason i had to reinstall all the node modules i'm using, to do that i use `npm`. 
The version installed for `medium-draft` was `0.3.13` and apparently it did not work(seemed like the `onChange` event never fires).

After some investigation i went back to the version `0.3.12` and everything started working again. 

What i wonder is how stable is that version, i don't even seem that tag on the [releases](https://github.com/brijeshb42/medium-draft/releases).

**Comment by brijeshb42** [comment]
0.3.13 was published with the wrong dependency listing and in npm. I have deprecated/unpublished it now to avoid any such issues in future. Thanks for bringing this up.
Latest version is 0.4.0 and before that, 0.3.12.
