### ISSUE TITLE
OnChange event is called when the editor data is populated 

### ISSUE THREAD

**Issue by riccardolorenzon** [brijeshb42/medium-draft#32]
I use a Ajax call to get the last data from the back end, the data flows to the component correctly. 

What i also see is that the `onChange` event is called multiple times as the component data is populated. 

I wonder if this is the expecting behavior, because with all the other components i use the `onChange` method is not triggered unless the user attempts to modify the component's value.

**Comment by brijeshb42** [comment]
Any simple demo to checkout ?
Meanwhile, are you also focussing/blurring the editor while fetching the new data? Blur/focus also calls `onChange`.

**Comment by riccardolorenzon** [comment]
It's definitely because  of the focus event i call when the component is mounted. 

I flow the data from the parent component when this is mounted, what i think now is that i can't assume that when a parent component is mounted the children are mounted as well.
