### ISSUE TITLE
JSON.parse(mySavedEditorData) results in an error

### ISSUE THREAD

**Issue by Method-X** [brijeshb42/medium-draft#34]
I'm trying to load the editor with previously saved data (convertToRaw) but am getting the following error: `VM123741:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0`

Note that I used the following to save to mongodb: `convertToRaw(this.state.instructions.getCurrentContent())`

**Comment by brijeshb42** [comment]
From the error, it seems like you are using python in the backend. It's JSON data may have the form of

```python
{
u'key': u'value'
} 
```
You should try returning the data using json.dumps to properly convert the python dictionary to json.

**Comment by Method-X** [comment]
@brijeshb42 I'm using Meteor on the backend.

**Comment by brijeshb42** [comment]
Can you see what the server is sending in the response? It is not valid json
On Nov 30, 2016 7:15 AM, Matt MacPherson <notifications@github.com> wrote:@brijeshb42 I'm using Meteor on the backend.

**Comment by Method-X** [comment]
<img width="566" alt="screen shot 2016-11-29 at 9 00 38 pm" src="https://cloud.githubusercontent.com/assets/8339427/20736808/f4e180ac-b676-11e6-981e-4fef9804e174.png">

**Comment by Method-X** [comment]
I can convert to HTML just fine:

```
  convertToHTML () {
    var text = convertFromRaw(this.props.text)
    return stateToHTML(text)
  }
```

`{renderHTML(this.convertToHTML())}`

**Comment by brijeshb42** [comment]
Can your try this 
```javascript
import {createEditorState} from medium-draft ;

const es = createEditorState(yourJsonData) ;
```

**Comment by Method-X** [comment]
<img width="504" alt="screen shot 2016-11-29 at 9 42 43 pm" src="https://cloud.githubusercontent.com/assets/8339427/20737755/cfd28e40-b67c-11e6-85c3-d10bb387934c.png">

**Comment by Method-X** [comment]
So apparently I didn't have to parse the JSON object at all.
