### ISSUE TITLE
First click on side buttons make the element disappear

### ISSUE THREAD

**Issue by codeKonami** [brijeshb42/medium-draft#38]
When you load the page and click directly on the side buttons the element disappear completely.

![Bug](https://champagne-supernova.s3-eu-west-1.amazonaws.com/9b98ed06-047f-485d-be64-c541df807d53.gif)

**Comment by brijeshb42** [comment]
I have also observed this behavior. I am not sure why this occurs. Somethibg twisted to draft's selection collapse maybe.

**Comment by yachtingchen** [comment]
Here is a simple workaround for this problem

`import React from 'react';

import {
  Editor,
  createEditorState,
} from 'medium-draft';

class MediumEditor extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      editorState: createEditorState(),
      hideWorkaround: false
    };

    this.onChange = (editorState) => {
      this.setState({ editorState });
    };
  }

  componentDidMount() {
    this.refs.editor.focus();
    /* workaround code start */
    setTimeout(() =>  this.refs.workaround.focus(), 50);
    setTimeout(() =>  this.refs.editor.focus(), 100);
    setTimeout(() =>  this.setState({hideWorkaround: true}), 70);
    /* workaround code end */
  }

  render() {
    const { editorState } = this.state;
    return (
      <div>
        <input hidden={this.state.hideWorkaround} ref="workaround" />
        <Editor
          ref="editor"
          editorState={editorState}
          onChange={this.onChange} />
      </div>
    );
  }
}

export default MediumEditor;`

**Comment by yachtingchen** [comment]
Similar problem happened when the cursor is in "image caption" and press "Enter"

![disapear](https://cloud.githubusercontent.com/assets/8899072/23192580/392c9cc4-f8df-11e6-8e2d-a32171dbeb9e.gif)

**Comment by J00nz** [comment]
https://github.com/brijeshb42/medium-draft/pull/62
