### ISSUE TITLE
You should probably add RTL support to the list of futures :)

### ISSUE THREAD

**Issue by shahinism** [brijeshb42/medium-draft#43]
As far as I tried, it works perfectly, without even trying to change anything (thanks for the awesome job):
![selection_056](https://cloud.githubusercontent.com/assets/698857/21451163/1ebcacdc-c912-11e6-9ed9-eaed9bbda034.png)
 And this is a future that you can't find it original medium editor :wink:

**Comment by brijeshb42** [comment]
This feature comes with draft js which `medium-draft` uses internally. So kudos to that project. 

As you suggested, I will add this as a feature in the README
