### ISSUE TITLE
include preprocessed CSS file to change font-family?

### ISSUE THREAD

**Issue by arfianadam** [brijeshb42/medium-draft#44]
Hi! I love your work and I am using it in my project. One problem though, the font-family is set and hardcoded in the `index.css` file. Meaning I have to go through the file and change every `font-family` statement. Is there anyway we can include the SASS or LESS file so we can add some variables for the font?

Like:
```sass
$font-sans-serif: Helvetica, sans-serif;
$font-serif: Georgia, serif;
```

Thank you!

**Comment by brijeshb42** [comment]
I actually should not have hardcoded fonts in the `index.css` file. Right now there are 3 fonts hardcoded in the file. But you can easily override those for now. Next release will not have those in the default css file. Users will have to add their own fonts if they want.

**Comment by arfianadam** [comment]
Right. Thanks for the clarification. I might as well try to contribute to this also :grinning:

**Comment by brijeshb42** [comment]
I would like to limit inline css usage in `react` to just positional properties.

Every block type has a relevant classname which can be easily used to customise the font. So I would basically like to remove the specific hardcoded styles from the inbuilt css so that users can add their own styles.

**Comment by brijeshb42** [comment]
Removed the fonts outside the core styling. You now have to add your own fonts.
