### ISSUE TITLE
Is it possible to add 'remove link' feature?

### ISSUE THREAD

**Issue by lipenco** [brijeshb42/medium-draft#45]
So far we can add links, but not remove it. Seems like a bug.

**Comment by brijeshb42** [comment]
I initially thought about adding a button to remove the link in a single click. But took a decision not to add it to make one less btn. Instead, if you have to remove a link, you can click the add link button on the selected link text and clear the href value in input and press enter. The link will be removed.

**Comment by lipenco** [comment]
ok, that makes sense. thanks
