### ISSUE TITLE
Can't add ref to medium-draft

### ISSUE THREAD

**Issue by haluvibe** [brijeshb42/medium-draft#46]
Why are you using strings as your ref for medium-draft in your example?

Isn't that legacy? Anyway, it doesn't work and this.refs is just an empty object.

How do I get this to work with the modern ref={(c) => this._input = c}

**Comment by brijeshb42** [comment]
I just converted all the string refs in the example to new refs and everything is working fine. Not sure about your issue though. You can check that in the demo.

**Comment by haluvibe** [comment]
thx!!!
