### ISSUE TITLE
Can't save output to firebase

### ISSUE THREAD

**Issue by haluvibe** [brijeshb42/medium-draft#47]
The issue here is that 'undefined' is not a type in JSON, and it's not something that Firebase can store. 

When I try and save Editor state to firebase I get the following error message

Uncaught Error: Firebase.push failed: first argument contains undefined in property 'somePath.articles.editorState._immutable._map._root.entries.0.1._map._root.entries.0.1._map.__ownerID'

**Comment by haluvibe** [comment]
So I guess my question is, how can I change the value of editorState._immutable._map._root.entries.0.1._map._root.entries.0.1._map.__ownerID' as it seems to be immutable?????

**Comment by haluvibe** [comment]
Should I saving the editorState to firebase at all? Is there a better way to persist data than trying to save this.state.editorState?

**Comment by brijeshb42** [comment]
https://github.com/brijeshb42/medium-draft/wiki/Persisting-Editor-Data

You should not send the internal immutable data structure that `draft-js` uses to your backend. First convert the data to json like this -

```
import { convertToRaw } from 'draft-js';
const editorData = convertToRaw(this.state.editorState.getCurrentContent());
```

Here `editorData` can be converted to string using `JSON.stringify(editorData)` or directly sent as json to whatever backend you are using.

**Comment by haluvibe** [comment]
thx!!!!
