### ISSUE TITLE
Empty Block appears when dragging image or using EmbedSideButton

### ISSUE THREAD

**Issue by mezod** [brijeshb42/medium-draft#51]
I have manipulated your examples code as little as possible but for these two cases, when drag and dropping an image and when embedding a video from the sidebuttons, and empty block is created by default before the img block. I can't delete it from the editor without deleting the image/video.

My handleDropped code looks like:

```
handleDroppedFiles(selection, files) {
    const file = files[0];
    if (file.type.indexOf('image/') === 0) {
      // const src = URL.createObjectURL(file);

      const formData = new FormData();
      formData.append('image', file, file.name);

      imageUpload(formData).then(path => {
        const src = path.path;

        this.onChange(addNewBlockAt(
          this.state.editorState,
          selection.getAnchorKey(),
          Block.IMAGE, {
            src,
          }
        ));
        return HANDLED;
      });
    }
    return NOT_HANDLED;
  }
```

This is how it looks now, I just create a formData to be able to add it to the body when making a POST request (imageUpload is basically the request) and then I get the path where the file is stored and putting in the Block.IMAGE, as it was before 
I don't add any blocks or anything, I drag the image into the empty editor and this is the resulting dom:

```
<div class="md-block md-block-paragraph" data-block="true" data-editor="34ndg" data-offset-key="cct11-0-0">...</div>
<figure class="md-block md-block-image" data-block="true" data-editor="34ndg" data-offset-key="1j3bh-0-0">...</figure>
```

For the video embed I literally copy your examples EmbedSideButton.jsx and AtomicEmbedComponent.jsx.

Adding an image from the SideButton doesn't have this issue.

Any ideas? How could I debug this? Let me know if you need more code samples!
Thanks!

**Comment by brijeshb42** [comment]
I think it's a problem with your `return HANDLED` statement. It's inside the callback unlike my example, in which there is no callback. You should return HANDLED outside your `imageUpload` promise.

**Comment by brijeshb42** [comment]
Also, empty blocks before/after atomic/embed blocks cannot be prevented. It's just how draft-js handles them. You can  remove the empty blocks yourself programmatically though
