### ISSUE TITLE
Todo check boxes do not work on Firefox

### ISSUE THREAD

**Issue by TioSeuss** [brijeshb42/medium-draft#56]
This might be a bit trivial, but I noticed in the demo that the checkboxes weren't working on Firefox when I was testing it. I really like Medium-Draft and I was thinking of having my team integrate it into our platform, so I wanted to give you guys a heads up. 

Thanks.

**Comment by brijeshb42** [comment]
Although I checked `medium-draft` in general in Firefox, I never really checked the todo list. Thanks for reporting.

**Comment by TioSeuss** [comment]
Thank you for the prompt follow up and thank you for this awesome draft.js library!

**Comment by brijeshb42** [comment]
Fixed in latest commit. Will be shipped to npm in next release.
