### ISSUE TITLE
Empty spaces above and below images

### ISSUE THREAD

**Issue by stev3reed** [brijeshb42/medium-draft#57]
Is there a solution for getting rid of the the empty paragraph blocks above and below an image in the editor? What's the best way to deal with them?

`<div class="md-block md-block-paragraph" data-block="true" data-editor="66e9a" data-offset-key="2vr7c-0-0"><div data-offset-key="2vr7c-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="2vr7c-0-0"><br data-text="true"></span></div></div>`

**Comment by brijeshb42** [comment]
Not able to duplicate
