### ISSUE TITLE
Opposite of mediumDraftExporter (convertFromHTML)?

### ISSUE THREAD

**Issue by akinnee** [brijeshb42/medium-draft#58]
It seems that this library has provided an export function, but not an import function. `draft-convert` supports both. I'm attempting to implement the reverse (import), but I'm new to this library and draft-convert, so it's somewhat challenging. Do you have any plans to implement `convertFromHTML`?

**Comment by brijeshb42** [comment]
There is no plan for this feature in the immediate future. If enough requests come, I may consider it.

**Comment by akinnee** [comment]
Ok. No problem. I may end up submitting a PR.

**Comment by SteveAdams** [comment]
http://draftjs.org/docs/api-reference-data-conversion.html#convertfromhtml

Does this accomplish what you're looking for?

**Comment by akinnee** [comment]
In the sense that I have to write all of the handlers myself, yes. ;P
