### ISSUE TITLE
How to display icon instead of text in toolbar

### ISSUE THREAD

**Issue by ouabing** [brijeshb42/medium-draft#64]
I'm searching for a way to display icon instead of text in toolbar. I just noticed that [these lines](https://github.com/brijeshb42/medium-draft/blob/13372c9d3d5cacea6e1042b7a9e77e923fbc5708/src/components/blocktoolbar.js#L19-L23) were just commented out. I found it working pretty well after I uncommented these lines. Is there any problem to these lines?

Thanks.

**Comment by brijeshb42** [comment]
The icons present an issue when the font files of font awesome are not loaded. Browser tries to load the files when the icons become visible. But I require to calculate the width of the toolbar which is not available when files are not loaded

**Comment by brijeshb42** [comment]
This issue has been resolved with the latest release. You can now pass react components in `label` instead if just string for button styling. See https://github.com/brijeshb42/medium-draft/blob/master/src/components/toolbar.js#L350

**Comment by ouabing** [comment]
Thanks!
