### ISSUE TITLE
Update to React 15.5 

### ISSUE THREAD

**Issue by riccardolorenzon** [brijeshb42/medium-draft#67]
Apparently the component is not updated to the latest version of React. 
Specifically in the new version `React.PropTypes` has been moved to its own package. 
This triggers the following exception: 
`Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead`

**Comment by brijeshb42** [comment]
You can update the react installation in your project if you want. Anyways, `medium-draft` does not has a dependency on any exact version of react. In its package.json, it's >=15.0. So you can update your react

**Comment by neurosnap** [comment]
The problem is that this package is using `PropTypes` which is no longer inside the react project.  This project needs to pull in `prop-types`.

https://www.npmjs.com/package/prop-types

**Comment by baldwmic** [comment]
@brijeshb42 I've opened a pr at #73 for migrating React to v15.5.

The main argument for doing this is the `medium-draft` codebase uses `React.PropTypes` which is no longer possible in new versions of React. `prop-types` is now a separate package. So, even though `react` is a peer dependency in the package.json of `medium-draft`, there is code that is using an old version of React.
