### ISSUE TITLE
How to inset text data in draft editor

### ISSUE THREAD

**Issue by MCD-50** [brijeshb42/medium-draft#68]
I want to insert text to draft editor ie before writing. I have a file that contains text and I want to load the text in draft editor.

**Comment by pradel** [comment]
On your constructor you should pass your data to `createEditorState`.
```javascript
     this.state = {
      editorState: createEditorState(data), // with content
    };
```

**Comment by MCD-50** [comment]
const data = "this is my data". 
editorState: createEditorState(data)
//giving error 


can you mention the structure of data;
Thanks.

**Comment by pradel** [comment]
I think it correspond to `RawDraftContentState` from draft-js.
You should take a look at the draft-js documentation. https://draftjs.org/docs/api-reference-data-conversion.html
