### ISSUE TITLE
Support for Image and Video via Media Manager Dialog

### ISSUE THREAD

**Issue by agungsb** [brijeshb42/medium-draft#7]
Is there any plan to support image and video picker via media manager dialog in the future?

**Comment by brijeshb42** [comment]
Yes there is an ongoing plan to add support for adding image blocks and embeds just like medium.com . In the demo, if you goto a new empty line, you can see the **(+)** button on the side of the text block. This will eventually have the image/embed adding feature. I don't have a timeline yet as I am currently researching ways to add images/embeds alongwith captions such that one can also add inline styles to the caption text.

**Comment by brijeshb42** [comment]
I am not sure about what you mean by a media-manager dialog. Do you mean like a modal with images from where users can select an image ? If that is the case, then I think that use case is very specific to your needs. You may have to fork and implement that particular feature yourself if you plan to use this project.

**Comment by brijeshb42** [comment]
Just implemented image block. You can check out the demo.
