### ISSUE TITLE
Set text cursor to the end of the input on focus?

### ISSUE THREAD

**Issue by krstffr** [brijeshb42/medium-draft#71]
`this.editor.focus()` sets the cursor at the beginning of the input, what is the preffered way of setting it at the end?

(Sorry if this has been answered before, searched the issues for "focus" and couldn't seem to find any related issues.)

I'm on Mac/Chrome 57.0.2987.133.

**Comment by brijeshb42** [comment]
You can create another method call `focusAtEnd` and use `SelectionState` with `EditorState.forceSelection`. You will have to get the `key` of the last block to create and override the new `SelectionState`.

**Comment by brijeshb42** [comment]
Take a look at this file https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/moveSelectionToEnd.js

**Comment by krstffr** [comment]
@brijeshb42 thanks, I'll look into it today!

**Comment by comatory** [comment]
@brijeshb42 thanks for that link, saved my ass! Anyway I ran into this problem when I was manipulating the contents of `editorState` of my editor. Seems like `draft-js-plugins-editor` has tendency to move the cursor to the beginning after changing its contents. Maybe its intentional but for me the logical thing to do is move the cursor to last position.

**Comment by ladifire** [comment]
Draftjs has **moveSelectionToEnd(e: EditorState)** function. So to mo focus to end, you just need write this small piece of code:
`export function moveFocusToEnd(editorState: EditorState) {
    editorState = EditorState.moveSelectionToEnd(editorState);
    return EditorState.forceSelection(editorState, editorState.getSelection());
}`

**Comment by jenildesai25** [comment]
@ladifire Thank you for the solution. I tried but it did not work me. Would you be able to provide more code?

Thank you  :)
