### ISSUE TITLE
Toolbar in wrong position

### ISSUE THREAD

**Issue by bnwan** [brijeshb42/medium-draft#74]
The toolbar seems to appear in the wrong position:

![image](https://cloud.githubusercontent.com/assets/1225795/25658497/1906c37c-2ffb-11e7-9e40-0c5fc24d3a58.png)

Any help is appreciated

**Comment by brijeshb42** [comment]
Where is the selected text?

**Comment by bnwan** [comment]
Sorry...the first line is the selected text. lost focus when I did the screen shot. The toolbar seems to be displaying at the bottom of the editor

**Comment by brijeshb42** [comment]
Can't really help unless you have a demo page which I can take a look at.
