### ISSUE TITLE
links don't work for us on medium-draft 5.1

### ISSUE THREAD

**Issue by ryanxcharles** [brijeshb42/medium-draft#75]
Hi, we're using medium-draft at yours.org. Great job! This is an awesome editor.

Unfortunately when we post a link the link does not show up on the view page. Is there something we're doing wrong? We're using react and building things with webpack. We are including the medium-draft CSS.

**Comment by brijeshb42** [comment]
Something to do with decorators. What function are you using to create your `editorState` ?

**Comment by ryanxcharles** [comment]
We're using this method:

editorState = require('medium-draft').createEditorState()

**Comment by brijeshb42** [comment]
And what about for pre-existing content (besides the empty editor). I tested the editor @ https://www.yours.org/create/ and links were working fine.

**Comment by ryanxcharles** [comment]
Yes, you can create links, but when you actually post content, the links don't show up. It's empty text. We are using createEditorState both for the create page and the view page.

**Comment by ryanxcharles** [comment]
So to answer your question, for pre-existing content, we are doing it like this:

```
let editorState = convertFromRaw(JSON.parse(this.props.content.editor1State))
editorState = EditorState.createWithContent(editorState)
```

**Comment by brijeshb42** [comment]
You should try this instead

```js
editorState = createWithContent(JSON.parse(this.props.content.editorState))
```

**Comment by ryanxcharles** [comment]
OK, great, will try that!

**Comment by ryanxcharles** [comment]
When I try that, I get this error on the view page:

<img width="531" alt="screen shot 2017-05-06 at 7 28 48 am" src="https://cloud.githubusercontent.com/assets/63740/25773166/b113b70e-322d-11e7-8892-901e0738c33b.png">

No content is displayed.

On the create page, here's how we're storing the data to our db:

```
let editorState = JSON.stringify(convertToRaw(this.state.editorState.getCurrentContent()))
```

On the view page, creating the editor now looks like this:

```
let editorState = EditorState.createWithContent(JSON.parse(this.props.content.editorState))
```

**Comment by brijeshb42** [comment]
The input in `createWithContent` should be the JSON that you get from `convetToRaw`

**Comment by ryanxcharles** [comment]
OK great - I figured it out. Thank you!

The problem was we were using EditorState.createWithContent where EditorState was taken directly from draft-js. But by doing that, we weren't calling the decorators in medium-draft.

But what we should have been doing was using the createEditorState method from medium-draft, and passing in our content.

Here's the diff to show what fixed it:

```
-      let editorState = convertFromRaw(JSON.parse(this.props.content.editorState))
-      editorState = EditorState.createWithContent(editorState)
+      let editorState = createEditorState(JSON.parse(this.props.content.editorState))
```

Thank you very much for your help!
