### ISSUE TITLE
Can't apply inline styles to block style elements (from the buttons)

### ISSUE THREAD

**Issue by krstffr** [brijeshb42/medium-draft#79]
If I create a `<h1>` and want part of that `<h1>` to be in `<em>` like…

`<h1>Hello part of this is <em>in italic!</em></h1>`

…from clicking the styling buttons (**not using the `CMD+I` shortcut!**) I currently can't do that. Is this intentional? If yes: what's the reason behind it?

(To "reproduce", to to: http://bitwiser.in/medium-draft/ and highlight the first header and try to make part of it italic from the buttons: won't work!)

I need this since I add custom inline styling buttons which won't have keyboard shortcuts and I need to use the styling in some headlines.

**Comment by valthon** [comment]
I can't speak to the reasoning, but the the code does [explicitly and intentionally](https://github.com/brijeshb42/medium-draft/blob/master/src/editor.js#L395-L397) ignore attempts to apply styles to H1 blocks...

**Comment by brijeshb42** [comment]
I was basing this editor heavily on medium.com's at the time. And medium does not allow B, I styles on headings. That's why I also disabled it. I can merge if you submit a pull request for removing the behaviour.

**Comment by krstffr** [comment]
@brijeshb42 sure: https://github.com/brijeshb42/medium-draft/pull/80
