### ISSUE TITLE
Draft-js-plugins

### ISSUE THREAD

**Issue by bkniffler** [brijeshb42/medium-draft#8]
Hey, 
I'm the creator of http://draft-wysiwyg.herokuapp.com/

I love your medium-like draft editor, especially the keyboard-centric focus. Did you consider making medium-drafts features plugins for https://github.com/draft-js-plugins/draft-js-plugins ? 

It would modularize your efforts and allow to plugin things like drag and drop or image resizing without re-implementing these.

**Comment by brijeshb42** [comment]
I was thinking of migrating `medium-draft` to `draft-js-plugins` architecture. But right now, this project is too big to migrate singlehandedly. I will try to do this one step at a time though.

**Comment by samkuhn** [comment]
Just personally speaking, I would be tempted not to switch just yet.. I have spent a few days trying to use the draft-js-plugins architecture. I have found it pretty buggy and poorly documented. No offence to the authors - I think its heading in a great direction but not ready for the prime time IMO. I'm currently switching to medium-draft.
