### ISSUE TITLE
Inconsistent style

### ISSUE THREAD

**Issue by changhc** [brijeshb42/medium-draft#81]
Hello, I would like to report an inconsistent style.

In the editor, the **highlight** style is written inline:
```text-decoration: underline; background-color: yellow;```
However, when using basic.css to display the exported HTML in my page, the style has an extra entry ```padding: 2px 4px;```, which is different from what we saw in the editor.
Could you please fix this?

**Comment by brijeshb42** [comment]
`basic.css` has class `md-inline-highlight` to apply styles to highlight. You can always override the padding values with your own css.

**Comment by changhc** [comment]
Yes, but I just want to know why you decided to add padding to highlight in basic.css, rather than keeping both css identical.
