### ISSUE TITLE
Image Caption Paste Issue 

### ISSUE THREAD

**Issue by PengyuanZhao** [brijeshb42/medium-draft#83]
Pasting text to the image caption will remove the image. The image src will become undefined. Any way to fix this? Thanks!

**Comment by brijeshb42** [comment]
I will take a look this week.

**Comment by brijeshb42** [comment]
Fixed in https://github.com/brijeshb42/medium-draft/commit/5b527436ce24906d148d922a56d8ec760ca2cb13
