### ISSUE TITLE
Image Icon Missing

### ISSUE THREAD

**Issue by Nick-the-BinaryTree** [brijeshb42/medium-draft#84]
![image](https://user-images.githubusercontent.com/7897525/27865074-25f8a5f6-615f-11e7-8859-02b82a16b4e2.png)

I tried installing the font-awesome npm package and importing it.

I'm pretty sure this isn't proper ES6, but I also tried:
` import 'http://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css'`

Third, I tried importing the css directly:
`import "node_modules/font-awesome/..."`

But create-react-app won't let me import outside of the src folder.

Lastly, I tried copy and pasting the font-awesome css file into the src folder and deleting 2 lines where it links out using relative paths. This resulted in a little icon with 3 dots instead of an image icon.

Any ideas about getting this icon?

**Comment by brijeshb42** [comment]
Include the font file in your html

**Comment by Nick-the-BinaryTree** [comment]
Thanks, @brijeshb42.
That works in: `public/index.html` in a create-react-app project.
