### ISSUE TITLE
Button to remove all formatting

### ISSUE THREAD

**Issue by neurosnap** [brijeshb42/medium-draft#86]
Copying and pasting content into the editor will sometimes bring with it formatting.  How would you suggest allowing the user to remove that formatting?  I was thinking of a button in the toolbar, but I could not figure out how to add a custom button that I had full control over unless it fits in the block or inline paradigm.

**Comment by brijeshb42** [comment]
By removing formatting, you mean inline styles or anything else?

**Comment by neurosnap** [comment]
Inline styles, block stocks, and entities (hyperlinks)

**Comment by butsjoh** [comment]
You could look at https://github.com/jpuri/draftjs-utils maybe. It has a function i think to remove all things.

**Comment by neurosnap** [comment]
The main issue is there doesn't seem to be a way to add a button to the medium toolbar that lets me have full control.

This is sort of what I was thinking for an API: https://github.com/notion/medium-draft/pull/4

**Comment by brijeshb42** [comment]
Current development is going on in [this](https://github.com/brijeshb42/medium-draft/tree/v1-scalable) branch which will enable addition of custom commands / actions.

**Comment by butsjoh** [comment]
@brijeshb42 Will it also be possible now to hook into onUpArrow like it is possible with handleKeyCommand, handleBeforeInput, handleReturn  (by passing a custom implementation through props)?

As i see in the new code you would be able to define your own handlers which would allow to do this not?

Any idea on when you are going to release that work?

thnx and keep up the good work

**Comment by brijeshb42** [comment]
@butsjoh I am targeting this weekend for the feature release.

**Comment by butsjoh** [comment]
@brijeshb42 Did say any release :) Could you still push soon? My code already adapted to the v1-scalable branch and would like to remove the local npm install. thnx
