### ISSUE TITLE
Unable to build with npm run build

### ISSUE THREAD

**Issue by Swapnilchavan18** [brijeshb42/medium-draft#88]
NODE_PATH=src babel-node ./node_modules/.bin/isparta cover _mocha -- --growl --compilers js:babel-core/register,css:test-js/css-null-compiler.js --require ./test-js/test_helper.js $(find src -path '*.spec.js')

sh: 1: babel-node: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! medium-draft@0.5.2 test:unit: `NODE_PATH=src babel-node ./node_modules/.bin/isparta cover _mocha -- --growl --compilers js:babel-core/register,css:test-js/css-null-compiler.js --require ./test-js/test_helper.js $(find src -path '*.spec.js')`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the medium-draft@0.5.2 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by brijeshb42** [comment]
https://stackoverflow.com/a/18020195/2986924

**Comment by Swapnilchavan18** [comment]
I dont exactly remember what was wrong. Worked later. Thanks
