### ISSUE TITLE
Capture cmd+enter command, where?

### ISSUE THREAD

**Issue by krstffr** [brijeshb42/medium-draft#89]
Let's say I want to save some data when user hits cmd+enter (or ctrl+enter on PC) from inside the medium editor. Where would I hook in this logic? I tried looking into the `beforeInput` function, but it don't gets passed any keyboard events (or is it?). Same with `onChange`, it only gets passed the `editorState`. 

(Sorry if there is actually a third function which I've missed!) 👍

**Comment by brijeshb42** [comment]
Take a look at this file https://github.com/brijeshb42/medium-draft/blob/master/src/util/keybinding.js
