### ISSUE TITLE
Enable links in edit mode

### ISSUE THREAD

**Issue by mezod** [brijeshb42/medium-draft#90]
Hi, I have noticed that while on edit mode links are disabled. How can I enable them?

The use case would be that of evernote or gmail, where draftjs is always in edit mode (for notetaking) but links should still be clickable.

Thank you!

**Comment by brijeshb42** [comment]
Links are not disabled in any mode. Its just that it is in contentEditable mode. `medium-draft` shows a tooltip with the same url which you can click to goto that url. You cannot navigate to a url while also trying to edit it.

![screen shot 2017-08-20 at 9 11 17 pm](https://user-images.githubusercontent.com/717550/29496225-23702992-85ec-11e7-8fa2-7034928aa648.png)

**Comment by mezod** [comment]
The tooltip is not clickable for me, do I have to define it as clickable somewhere?

**Comment by brijeshb42** [comment]
Whole tooltip is not clickable. Only the link text part is. Test it out in the demoThanks. Brijesh On Aug 20, 2017 9:16 PM, Joan Boixadós <notifications@github.com> wrote:The tooltip is not clickable for me, do I have to define it as clickable somewhere?

**Comment by mezod** [comment]
hmm I see the tooltip is different in the demo, it works there, I might have an older version

**Comment by mezod** [comment]
Yep, had an old version :_) Thanks @brijeshb42 !
