### ISSUE TITLE
Request Example For Persisting Uploaded Image

### ISSUE THREAD

**Issue by SevenZark** [brijeshb42/medium-draft#93]
First of all, this is a great library. I found it easy to set up and get running.

So is there an example somewhere of how to persist an uploaded image to db? If not, that would be nice, for those of us not super familiar with what it would take to do that. And if it is not too complex.

I notice that when I convertToRaw, for an uploaded image I wind up with a block of type 'atomic:image' whose data object contains one key called 'src,' that is basically an href to a serialized URI on my local dev server. So obviously there is more lifting I'm meant to do, but I've been googling to try to figure that out for days and come up with nothing. I don't know much about dealing with blob form inputs or whatever this is under the hood (and also wasn't able to figure out much about that from searching either).

I'm also willing to contribute written documentation to the medium-draft project to provide the example if somebody is willing to help me figure out how to solve the problem but doesn't have the time to write the docs.

**Comment by brijeshb42** [comment]
The solution for the use case that you are looking for is mentioned briefly in *Customizing Side buttons* section of the [readme](https://github.com/brijeshb42/medium-draft/blob/master/README.md#customizing-side-buttons). Take a look. We can discuss more after that if you want.

**Comment by SevenZark** [comment]
That is exactly what I'm looking for! I did not think to look in that section of the docs to find out about file uploads. Thank you so much for your response. This is a big help.
