### ISSUE TITLE
Adding custom blocks

### ISSUE THREAD

**Issue by THook** [brijeshb42/medium-draft#94]
Hi,

I have been playing around with medium-draft (basic use cases then updating image block. I now would like to add custom blocks - which seemed pretty straightforward but doesn't work right now.

Here are the steps I took :

first, adding a video.js file in components/blocks/
This really is an example, almost copy-pasted from blocks/image.js

<img width="792" alt="screen shot 2017-08-25 at 21 48 27" src="https://user-images.githubusercontent.com/6568065/29730206-8b56317c-89df-11e7-8c35-5c1b030f1fed.png">

Then, I added a custom side button, like you did with Break and Image :

<img width="793" alt="screen shot 2017-08-25 at 21 55 22" src="https://user-images.githubusercontent.com/6568065/29730425-692198d4-89e0-11e7-971b-4a8d5fe5bb70.png">

Basically, it just prompts user to input a video url and then just updates the editor state with the new video block.

Then, updating Block constants in util/constants

<img width="402" alt="screen shot 2017-08-25 at 21 47 16" src="https://user-images.githubusercontent.com/6568065/29730261-cc95d00c-89df-11e7-972a-b04e475f83b4.png">

After that, I just added _constants.Block.IMAGE switch case to custorerenderer.js :

<img width="425" alt="screen shot 2017-08-25 at 21 46 54" src="https://user-images.githubusercontent.com/6568065/29730291-eb6faa70-89df-11e7-974e-486d32951f0d.png">

Adding Video custom block gives me an "Uncaught TypeError: Cannot read property 'wrapper' of undefined at DraftEditorContents.render". Funny enough, replacing the call to video block by image block in customrerenderer.js gives me the exact same error...

Am I missing a step?

Thanks for your time!

Hugo

**Comment by brijeshb42** [comment]
Can you provide a more detailed stack trace?

**Comment by StarAzure** [comment]
@hypervillain Hi - How did you solve that error? `TypeError: Cannot read property 'wrapper' of undefined` 

Thanks

**Comment by AliN11** [comment]
@hypervillain Can you please tell me how I can add a custom block? Any link, tutorial, ...
